version: '3.8'
services:
    movie-db:
        environment:
            - DEBUG=startup,api,database
        image: movie-db
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname==${THISHOST}