#!/bin/bash

export THISHOST=`hostname`

docker stack rm movie-db

git pull && \
docker build . -t movie-db && \
echo "wait 15 seconds for stack to shut down" && \
sleep 15 && \
docker stack deploy -c docker-compose.yml movie-db
