services:
    db:
        environment:
            - DEBUG=startup,api,database
        image: movie-db
        ports:
            - '80:29099'
    nginx:
        image: docker.io/nginx:stable-alpine
        restart: always
        depends_on:
            - db
        ports:
            - 443:443
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf:Z
            - ./passwd:/etc/nginx/basic_auth:Z
            - ./host.crt:/etc/ssl/certs/nginx/host.crt:Z
            - ./host.key:/etc/ssl/certs/nginx/host.key:Z
