version: '3.3'
services:
    movie-db:
        environment:
            - DEBUG=startup,api,database
        image: movie-db
        networks:
            - iSxS
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname==${THISHOST}
networks:
    iSxS:
        external:
            name: host
